# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Vite React App to Azure

on:
  push:
    branches:
      - main     # Change if your main branch has a different name
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: windows-latest    # Or ubuntu-latest if you prefer Linux

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Use your Node.js version here

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist          # Upload only the production build folder

  deploy:
    runs-on: windows-latest   # Or ubuntu-latest

    needs: build              # Waits for build job to finish

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mortgagecalc'      # Your Azure App Service name
          package: './dist'              # Deploy from the build output folder
